// Contract ABIs used by the settler, server, web app and scripts (CONTRACTS.md §3–§4).
import { parseAbi } from 'viem'

export const coreAbi = parseAbi([
  'struct SettlementState { bytes32 stateRoot; uint64 lastEpoch; uint64 cursor; uint64 inboxCount; uint64 lastSettleAt; bool escaped; uint64 lastAsOf; uint80 lastPriceRoundId; }',
  'struct Params { uint64 grace; uint64 escapeDelay; uint64 maxSkew; uint64 maxPriceAge; }',
  'function settlementState() view returns (SettlementState)',
  'function params() view returns (Params)',
  'function inboxAcc(uint64) view returns (bytes32)',
  'function enclavePubKey() view returns (bytes)',
  'function pendingWithdraw(address, uint8) view returns (uint256)',
  'function deposit(uint8 asset, uint256 amount)',
  'function submitIntent(bytes blob)',
  'function requestWithdraw(uint8 asset, uint256 amount)',
  'struct Account { address addr; uint256 usdFree; uint256 usdReserved; uint256 ethFree; uint256 ethReserved; uint256 ethLocked; uint8 tier; uint256 repaidVolume; uint64 nonce; }',
  'function activateEscape()',
  'function exitAccount(Account a, bytes32[] proof)',
  'function verifyAccount(Account a, bytes32[] proof) view returns (bool)',
  'function claim()',
  'struct Loan { uint64 id; address borrower; uint8 tenorId; uint256 principal; uint32 rateBps; uint256 owed; uint256 collateral; uint8 tierAtOpen; uint64 openedAt; uint64 maturity; bytes32 lendersHash; }',
  'struct LenderShare { address lender; uint256 amount; }',
  'function escapeRepay(Loan l, LenderShare[] s, bytes32[] proof)',
  'function escapeLiquidate(Loan l, LenderShare[] s, bytes32[] proof)',
  'function claimUsd(address) view returns (uint256)',
  'function claimEth(address) view returns (uint256)',
  'function exited(address) view returns (bool)',
  'function resolved(uint64) view returns (bool)',
  'function verifyLoan(Loan l, bytes32[] proof) view returns (bool)',
  'function onReport(bytes metadata, bytes report)',
  // every TervaneCore custom error, so viem decodes reverts by name (ReceiverTemplate's forwarder check first)
  'error InvalidSender(address sender, address expected)',
  'error Escaped()',
  'error BadReportVersion()',
  'error BadEpoch(uint64 expected, uint64 got)',
  'error RootMismatch()',
  'error InboxOutOfRange()',
  'error InboxAccMismatch()',
  'error AsOfRegressed()',
  'error AsOfSkew()',
  'error PriceRoundRegressed()',
  'error PriceMismatch()',
  'error PriceStale()',
  'error TooManyPayouts()',
  'error PayoutExceedsRequest()',
  'error PayoutExceedsPending()',
  'error InvalidAsset()',
  'error ZeroAmount()',
  'error InvalidBlob()',
  'error ZeroAddress()',
  'error InvalidPubKey()',
  'error NotEscaped()',
  'error EscapeTooEarly(uint256 availableAfter)',
  'error NotAccountOwner()',
  'error NotBorrower()',
  'error AlreadyExited()',
  'error AlreadyResolved()',
  'error LendersMismatch()',
  'error InvalidProof()',
  'error NotLiquidatable()',
  'event InboxMessage(uint64 indexed index, uint8 indexed kind, address indexed sender, uint8 asset, uint256 amount, bytes blob)',
  'event EpochSettled(uint64 indexed epoch, bytes32 newRoot, uint64 inboxTo, uint64 asOf, int256 priceUsed)',
  'event Cleared(uint64 indexed epoch, uint8 indexed tenorId, uint32 rateBps, uint256 volume)',
  'event PayoutExecuted(uint64 indexed epoch, address indexed to, uint8 asset, uint256 requested, uint256 paid)',
  'event EscapeActivated(uint64 at)',
])

export const feedAbi = parseAbi([
  'function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)',
  'function getRoundData(uint80) view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)',
  'function updateAnswer(int256 answer)',
])

export const erc20Abi = parseAbi([
  'function balanceOf(address) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function mint(address to, uint256 amount)',
  'function faucet()',
])
